/**
 * Audit intake (Lane A) — the front door for the v0.1 Tier A hygiene loop.
 *
 * Sign in with GitHub → submit a repository you control → receive one-click
 * BYOC instructions (a caller workflow pinned to an immutable curationsx/yolo
 * commit). This module is wiring only: identity comes from `auth.ts`,
 * ownership evidence comes from `repository-verification.ts` (untouched), and
 * the refusal decisions live in the pure `evaluateIntake` below.
 *
 * Invariants honoured here (PRD-project-evidence-registry §6, §9.1):
 * - explicit submission — a URL is typed by the owner, never crawled;
 * - minimal identity — only the session login is read, no provider token;
 * - no repository write permission — we emit instructions, not commits;
 * - hygiene never runs on CURATIONS infrastructure — the caller workflow
 *   executes in the submitter's own GitHub Actions.
 */

import { getSession } from "./auth.ts";
import { json } from "./community.ts";
import type { Env } from "./env.ts";
import {
  verifyPublicRepository,
  type RepositoryEvidence,
} from "./repository-verification.ts";

/**
 * Immutable curationsx/yolo commit that callers pin for both the reusable
 * workflow reference and `audit_ref`. Update deliberately in a reviewed PR
 * (never a mutable branch name — see tools/watchdog-ducky-handoff.md).
 * Current pin: post-#61 main — includes the `previous_run` lineage input
 * (gap G3), so generated callers can produce truthful re-run deltas.
 */
export const AUDIT_WORKFLOW_PIN = "c72de4f77d64199a969c7466a83d614217facd84";

/** Path the caller creates in their own repository. */
export const CALLER_WORKFLOW_PATH = ".github/workflows/hygiene-audit.yml";

export const STRANGER_GUIDE_URL =
  "https://github.com/curationsx/yolo/blob/main/docs/audits/stranger-guide.md";

export type IntakeDecision =
  | { ok: true }
  | { ok: false; status: number; reason: string };

/**
 * Pure refusal logic — the falsifying proof target. A signed-in user asking
 * for a repository they do not control must be refused with a plain-language
 * reason (plan/vibe-coding-v0.1-foundation.md, Lane A).
 */
export function evaluateIntake(
  evidence: RepositoryEvidence,
  login: string,
): IntakeDecision {
  if (!evidence.submitter_matches_owner) {
    return {
      ok: false,
      status: 403,
      reason:
        `This intake only sets up audits for repositories owned by your ` +
        `signed-in GitHub account (@${login}). ` +
        `${evidence.owner}/${evidence.name} belongs to @${evidence.owner}, ` +
        `so we can't offer it here. If you own a fork of it, note that the ` +
        `v0.1 pilot audits source repositories only.`,
    };
  }
  if (evidence.archived === true) {
    return {
      ok: false,
      status: 400,
      reason:
        `${evidence.owner}/${evidence.name} is archived on GitHub. ` +
        `The audit would describe a frozen repository, so the v0.1 pilot ` +
        `skips archived repositories. Unarchive it or choose an active one.`,
    };
  }
  if (evidence.fork === true) {
    return {
      ok: false,
      status: 400,
      reason:
        `${evidence.owner}/${evidence.name} is a fork. The v0.1 pilot ` +
        `audits source repositories only, so the record always points at ` +
        `the code's home. Run the audit from the source repository instead.`,
    };
  }
  return { ok: true };
}

/**
 * The caller workflow the submitter commits to their own repository.
 * Deterministic function of (owner, name, commitSha) — both the reusable
 * workflow reference and audit_ref are pinned to the same immutable SHA.
 */
export function callerWorkflow(
  owner: string,
  name: string,
  commitSha: string,
): string {
  return `name: Tier A hygiene audit
# Runs in YOUR GitHub Actions (your compute, your billing).
# Generated by curations.dev audit intake — see ${STRANGER_GUIDE_URL}

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Full 40-character commit SHA to audit (defaults to the SHA pinned below)"
        required: false
        default: "${commitSha}"
        type: string
      previous_run:
        description: "run_id of your previous run-record (re-runs only; enables a truthful delta)"
        required: false
        default: ""
        type: string

permissions:
  contents: read

jobs:
  audit:
    uses: curationsx/yolo/.github/workflows/hygiene-audit-reusable.yml@${AUDIT_WORKFLOW_PIN}
    with:
      repo_url: https://github.com/${owner}/${name}.git
      commit_sha: \${{ inputs.commit_sha }}
      audit_ref: ${AUDIT_WORKFLOW_PIN}
      previous_run: \${{ inputs.previous_run }}
`;
}

interface GitHubCommitResponse {
  sha?: string;
}

/** Resolve the default branch head so the caller audits an immutable commit. */
async function resolveHeadSha(
  owner: string,
  name: string,
  branch: string,
  token?: string,
): Promise<string | null> {
  try {
    const headers: Record<string, string> = {
      accept: "application/vnd.github+json",
      "user-agent": "curations.dev audit intake",
      "x-github-api-version": "2022-11-28",
    };
    if (token) headers.authorization = `Bearer ${token}`;
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${name}/commits/${encodeURIComponent(branch)}`,
      { headers, signal: AbortSignal.timeout(5000) },
    );
    if (!response.ok) return null;
    const commit = (await response.json()) as GitHubCommitResponse;
    return commit.sha && /^[0-9a-f]{40}$/.test(commit.sha) ? commit.sha : null;
  } catch {
    return null;
  }
}

export async function handleAuditIntake(
  req: Request,
  env: Env,
  cors: Record<string, string>,
): Promise<Response> {
  const session = await getSession(req, env);
  if (!session) {
    return json(
      { error: "Sign in with GitHub to set up an audit for your repository." },
      401,
      cors,
    );
  }

  let repositoryUrl = "";
  try {
    const body = (await req.json()) as { repository_url?: unknown };
    if (typeof body.repository_url === "string") {
      repositoryUrl = body.repository_url.trim();
    }
  } catch {
    // fall through to the shared refusal below
  }
  if (!repositoryUrl) {
    return json(
      { error: "repository_url is required, e.g. https://github.com/you/your-repo" },
      400,
      cors,
    );
  }

  const verification = await verifyPublicRepository(
    "hygiene",
    repositoryUrl,
    "",
    "",
    session.user.login,
    env.GITHUB_REPOSITORY_TOKEN,
  );
  if (!verification.ok) {
    return json({ error: verification.error }, verification.status, cors);
  }

  const decision = evaluateIntake(verification.evidence, session.user.login);
  if (!decision.ok) {
    return json({ error: decision.reason }, decision.status, cors);
  }

  const branch = verification.evidence.default_branch ?? "main";
  const headSha = await resolveHeadSha(
    verification.evidence.owner,
    verification.evidence.name,
    branch,
    env.GITHUB_REPOSITORY_TOKEN,
  );
  if (!headSha) {
    return json(
      {
        error:
          `We could not resolve the head commit of ${branch} on ` +
          `${verification.evidence.owner}/${verification.evidence.name}, so we ` +
          `can't generate a pinned audit yet. Try again in a moment.`,
      },
      502,
      cors,
    );
  }

  return json(
    {
      repository: {
        owner: verification.evidence.owner,
        name: verification.evidence.name,
        default_branch: branch,
      },
      commit_sha: headSha,
      workflow_path: CALLER_WORKFLOW_PATH,
      workflow_yaml: callerWorkflow(
        verification.evidence.owner,
        verification.evidence.name,
        headSha,
      ),
      audit_ref: AUDIT_WORKFLOW_PIN,
      guide_url: STRANGER_GUIDE_URL,
      next_steps: [
        `Create ${CALLER_WORKFLOW_PATH} in your repository with the generated content.`,
        "Commit it to your default branch.",
        'Open the Actions tab, choose "Tier A hygiene audit", and press "Run workflow".',
        "Download the hygiene-run-record artifact when the run finishes — that JSON is your evidence.",
      ],
    },
    200,
    cors,
  );
}
